-- ============================================
-- SCHEMA REFACTOR: Remove Plot table, use Tile → Settlement directly
-- Generated: 2025-11-28
-- Migration Strategy: Data preservation before structure changes
-- ============================================

-- ============================================
-- STEP 1: DATA MIGRATION (Before dropping Plot table)
-- ============================================

-- 1.1 Migrate Plot quality ratings to Tile quality fields
-- Map Plot.rating (0.0-1.0) to Tile.*Quality (0-100 scale)
UPDATE "Tile" t
SET 
  "foodQuality" = CASE 
    WHEN t."primaryResource" = 'FOOD' THEN ROUND((p.rating * 100)::numeric, 0)::integer
    ELSE COALESCE(t."foodQuality", 0)
  END,
  "woodQuality" = CASE 
    WHEN t."primaryResource" = 'WOOD' THEN ROUND((p.rating * 100)::numeric, 0)::integer
    ELSE COALESCE(t."woodQuality", 0)
  END,
  "stoneQuality" = CASE 
    WHEN t."primaryResource" = 'STONE' THEN ROUND((p.rating * 100)::numeric, 0)::integer
    ELSE COALESCE(t."stoneQuality", 0)
  END,
  "oreQuality" = CASE 
    WHEN t."primaryResource" = 'ORE' THEN ROUND((p.rating * 100)::numeric, 0)::integer
    ELSE COALESCE(t."oreQuality", 0)
  END
FROM "Plot" p
WHERE t.id = p."tileId";

-- 1.2 Migrate Plot ownership to Tile.settlementId
UPDATE "Tile" t
SET "settlementId" = p."settlementId"
FROM "Plot" p
WHERE t.id = p."tileId" AND p."settlementId" IS NOT NULL;

-- 1.3 Migrate SettlementStructure.plotId to tileId + slotPosition
-- Add slotPosition column (before renaming plotId)
ALTER TABLE "SettlementStructure" ADD COLUMN "slotPosition" integer;

-- Populate tileId from Plot.tileId (temporary column for data migration)
ALTER TABLE "SettlementStructure" ADD COLUMN "tileId_temp" text;

UPDATE "SettlementStructure" ss
SET "tileId_temp" = p."tileId"
FROM "Plot" p
WHERE ss."plotId" = p.id;

-- Assign slotPosition based on structure order per tile
-- (For simplicity, assign sequential slot positions 0, 1, 2, ...)
WITH numbered_structures AS (
  SELECT 
    id,
    ROW_NUMBER() OVER (PARTITION BY "tileId_temp" ORDER BY "createdAt") - 1 AS slot_num
  FROM "SettlementStructure"
  WHERE "tileId_temp" IS NOT NULL
)
UPDATE "SettlementStructure" ss
SET "slotPosition" = ns.slot_num
FROM numbered_structures ns
WHERE ss.id = ns.id;

-- ============================================
-- STEP 2: STRUCTURE CHANGES (Generated by Drizzle)
-- ============================================

-- Drop Plot table (all data migrated above)
ALTER TABLE "Plot" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP TABLE "Plot" CASCADE;--> statement-breakpoint

-- Rename plotId to tileId (will use tileId_temp data)
ALTER TABLE "SettlementStructure" RENAME COLUMN "plotId" TO "tileId";--> statement-breakpoint

-- Copy data from temp column to renamed column
UPDATE "SettlementStructure" SET "tileId" = "tileId_temp";

-- Drop temp column
ALTER TABLE "SettlementStructure" DROP COLUMN "tileId_temp";

-- Drop old Plot foreign key constraint (already dropped by CASCADE)
-- ALTER TABLE "SettlementStructure" DROP CONSTRAINT "SettlementStructure_plotId_Plot_id_fk";
--> statement-breakpoint

-- Drop old index
DROP INDEX IF EXISTS "SettlementStructure_plotId_idx";--> statement-breakpoint

-- Add new foreign key to Tile
ALTER TABLE "SettlementStructure" ADD CONSTRAINT "SettlementStructure_tileId_Tile_id_fk" FOREIGN KEY ("tileId") REFERENCES "public"."Tile"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint

-- Create new index on tileId
CREATE INDEX "SettlementStructure_tileId_idx" ON "SettlementStructure" USING btree ("tileId");

-- ============================================
-- STEP 3: VALIDATION (Optional sanity checks)
-- ============================================

-- Verify no null tileIds in SettlementStructure
DO $$
DECLARE
  null_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO null_count FROM "SettlementStructure" WHERE "tileId" IS NULL;
  IF null_count > 0 THEN
    RAISE WARNING 'Found % SettlementStructure records with null tileId after migration', null_count;
  END IF;
END $$;

-- Verify all structures have valid slotPosition
DO $$
DECLARE
  invalid_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO invalid_count FROM "SettlementStructure" WHERE "slotPosition" IS NULL;
  IF invalid_count > 0 THEN
    RAISE WARNING 'Found % SettlementStructure records with null slotPosition after migration', invalid_count;
  END IF;
END $$;

-- Migration complete
-- Plot table removed, data migrated to Tile-based structure